/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myhospital;

import java.awt.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Administrator
 */




public class HosLoginJDialog extends javax.swing.JDialog {

    /**
     * Creates new form LoginJDialog
     */
    private static DBProcess db = null;
    Vector mainVector = null;
    int cnt = 3;
    public static String DEPT_NO_True = "0";
    public static String PAS_USER_True = null;
    public static String DEPT_NAME_True = null;
    
    public HosLoginJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        mainVector = new Vector();
        db = new DBProcess();
        
        setLocationRelativeTo(null);
        setResizable(false);
        setB();
    }
    
    public HosLoginJDialog() {
        initComponents();

        mainVector = new Vector();
        db = new DBProcess();
        
        setLocationRelativeTo(null);
        setResizable(false);
        setB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDG_ErrorLogin = new javax.swing.JDialog();
        jB_ErrorOK = new javax.swing.JButton();
        jL_ErrorTitle = new javax.swing.JLabel();
        jLLogin = new javax.swing.JLabel();
        jLUser = new javax.swing.JLabel();
        jTFUser = new javax.swing.JTextField();
        jLPassword = new javax.swing.JLabel();
        jBLogin = new javax.swing.JButton();
        jBCannel = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        jDG_ErrorLogin.setSize(new java.awt.Dimension(350, 200));

        jB_ErrorOK.setText("确定");
        jB_ErrorOK.setPreferredSize(new java.awt.Dimension(90, 30));
        jB_ErrorOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ErrorOKActionPerformed(evt);
            }
        });

        jL_ErrorTitle.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N

        javax.swing.GroupLayout jDG_ErrorLoginLayout = new javax.swing.GroupLayout(jDG_ErrorLogin.getContentPane());
        jDG_ErrorLogin.getContentPane().setLayout(jDG_ErrorLoginLayout);
        jDG_ErrorLoginLayout.setHorizontalGroup(
            jDG_ErrorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDG_ErrorLoginLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jB_ErrorOK, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDG_ErrorLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_ErrorTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDG_ErrorLoginLayout.setVerticalGroup(
            jDG_ErrorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDG_ErrorLoginLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jL_ErrorTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jB_ErrorOK, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setForeground(new java.awt.Color(153, 153, 255));
        setSize(new java.awt.Dimension(368, 419));

        jLLogin.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        jLLogin.setText("和平医院登录界面");

        jLUser.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLUser.setText("请输入员工号");

        jTFUser.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N

        jLPassword.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLPassword.setText("请输入密码");

        jBLogin.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jBLogin.setText("确定");
        jBLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLoginActionPerformed(evt);
            }
        });

        jBCannel.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jBCannel.setText("取消");
        jBCannel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCannelActionPerformed(evt);
            }
        });

        jPasswordField1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLUser, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jBLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCannel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLLogin)
                .addGap(49, 49, 49)
                .addComponent(jLUser)
                .addGap(18, 18, 18)
                .addComponent(jTFUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCannel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jBLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginActionPerformed
        // TODO add your handling code here:
        jDG_ErrorLogin.setTitle("提示");
        jDG_ErrorLogin.setSize(350,200);
        jDG_ErrorLogin.setLocationRelativeTo(null);
        jDG_ErrorLogin.setResizable(false);
        jDG_ErrorLogin.setModal(true);
        String user = jTFUser.getText();
        String password = jPasswordField1.getText();
        
        if(user.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(null,"请输入用户名和密码","错误",JOptionPane.ERROR_MESSAGE);
        }
        else{
            while(cnt > 0){
            if(checkShenfen(user,password)){
                /*if("001".equals(DEPT_NO_True)){
                    this.setVisible(false);
                    new HospitalJFrame().setVisible(true);
                    break;
                }*/
                ///////////002/003/to be continue////////////////////////////////////////////////////
                this.setVisible(false);
                new HospitalJFrame().setVisible(true);
                break;
                
            }
            else{
                cnt--;
                if(cnt == 0)
                    System.exit(0);
                jL_ErrorTitle.setText("用户名或密码错误！你还剩余"+cnt+"次机会");
                jDG_ErrorLogin.setVisible(true);
            }
         break;
        } 
        }    
    }//GEN-LAST:event_jBLoginActionPerformed

    
    
    
    private void jB_ErrorOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ErrorOKActionPerformed
        // TODO add your handling code here:
        jDG_ErrorLogin.setVisible(false);
    }//GEN-LAST:event_jB_ErrorOKActionPerformed

    private void jBCannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCannelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jBCannelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HosLoginJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HosLoginJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HosLoginJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HosLoginJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HosLoginJDialog dialog = new HosLoginJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private boolean checkShenfen(String user,String password){
        //write sql
        String sql = "use MyHospital;select * from PASSWORD where PAS_USER='" + user + "';";
        System.out.println("checkShenfen : "+sql);
        String passwordTrue = null;
        
        db.connect();
        ResultSet rs = db.executeQuery(sql);
        
        try {
            rs.next();  //一定要有这一句，因为这时候光标在第一行的上面。The result set has no current row.
            passwordTrue = rs.getString("PAS_PASSWORD");
            DEPT_NO_True = rs.getString("DEPT_NO");
            PAS_USER_True = rs.getString("PAS_USER");
            setDEPT_NAME();
            if(!PAS_USER_True.equals("lyy")){
                setPAS_USER_True();
            }
            //System.out.println("passwordTrue = " + passwordTrue + ",dept_noTrue = " + dept_noTrue);
        } catch (SQLException ex) {
            System.out.println("SQLError.sql = " +sql);
            Logger.getLogger(HosLoginJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }catch (Exception e){
            System.out.println("Error.sql = " + sql);
        }
        
        db.disconnect();
        if(password.equals(passwordTrue))
            return true;

        return false;
    }
    
    private void setDEPT_NAME(){
        //DEPT_NAME_True
        //sql
        String sql = null;
        sql = "USE MyHospital;SELECT DEPT_NAME FROM DEPT " +
              "WHERE DEPT_NO = '"+DEPT_NO_True+"';";
        
        //
        db.connect();
        ResultSet rs = db.executeQuery(sql);
        
        //
        try {
            rs.next();  //一定要有这一句，因为这时候光标在第一行的上面。The result set has no current row.
            DEPT_NAME_True = rs.getString("DEPT_NAME");
        } catch (SQLException ex) {
            Logger.getLogger(HosLoginJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setPAS_USER_True(){
        //PAS_USER_True  "+PAS_USER_True+"
        //sql
        String sql = null;
        sql = "USE MyHospital;SELECT EMP_NAME FROM EMPLOYEE " +
              "WHERE EMP_NO = '"+PAS_USER_True+"';";
        
        //
        db.connect();
        ResultSet rs = db.executeQuery(sql);
        
        //
        try {
            rs.next();  //一定要有这一句，因为这时候光标在第一行的上面。The result set has no current row.
            PAS_USER_True = rs.getString("EMP_NAME");
        } catch (SQLException ex) {
            Logger.getLogger(HosLoginJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setB(){
         ImageIcon img = new ImageIcon("F:/UsingItems/MyHospital/back.jpg");//这是背景图片////////////////////////////////
         JLabel imgLabel = new JLabel(img);//将背景图放在标签里。
           this.getLayeredPane().add(imgLabel, new Integer(Integer.MIN_VALUE));//注意这里是关键，将背景标签添加到jfram的LayeredPane面板里。
           imgLabel.setBounds(0,0,img.getIconWidth(), img.getIconHeight());//设置背景标签的位置
           Container cp=this.getContentPane();
           cp.setLayout(new BorderLayout());
           ((JPanel)cp).setOpaque(false); //注意这里，将内容面板设为透明。这样LayeredPane面板中的背景才能显示出来。
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCannel;
    private javax.swing.JButton jBLogin;
    private javax.swing.JButton jB_ErrorOK;
    private javax.swing.JDialog jDG_ErrorLogin;
    private javax.swing.JLabel jLLogin;
    private javax.swing.JLabel jLPassword;
    private javax.swing.JLabel jLUser;
    private javax.swing.JLabel jL_ErrorTitle;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTFUser;
    // End of variables declaration//GEN-END:variables
}
