/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myhospital;
import java.awt.BorderLayout;
import java.awt.Container;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import myhospital.HosLoginJDialog;
/**
 *
 * @author Administrator
 */
public class HospitalJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HospitalJFrame
     */
    
    private Icon cure = new ImageIcon("cure.png");
    private Icon employee = new ImageIcon("employee.png");
    private Icon room = new ImageIcon("room.png");
    
    public HospitalJFrame() {
        initComponents();
        
        jL_Hello.setText("欢迎您！"+HosLoginJDialog.DEPT_NAME_True+"："+HosLoginJDialog.PAS_USER_True);
        setB();
        setLocationRelativeTo(null);
        setResizable(false);
        jB_Cure.setIcon(cure);
        jB_Employee.setIcon(employee);
        jB_Room.setIcon(room);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Hello = new javax.swing.JLabel();
        jB_Cure = new javax.swing.JButton();
        jB_Employee = new javax.swing.JButton();
        jB_Room = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jL_Hello.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jL_Hello.setText("欢迎您！");

        jB_Cure.setFont(new java.awt.Font("微软雅黑", 1, 36)); // NOI18N
        jB_Cure.setText("门诊部");
        jB_Cure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_CureActionPerformed(evt);
            }
        });

        jB_Employee.setFont(new java.awt.Font("微软雅黑", 1, 36)); // NOI18N
        jB_Employee.setText("员工管理");
        jB_Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_EmployeeActionPerformed(evt);
            }
        });

        jB_Room.setFont(new java.awt.Font("微软雅黑", 1, 36)); // NOI18N
        jB_Room.setText("住院部");
        jB_Room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_RoomActionPerformed(evt);
            }
        });

        jButton1.setText("切换登录");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_Hello, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_Cure, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jB_Room, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jB_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Hello, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Cure, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Room, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_CureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_CureActionPerformed
        // TODO add your handling code here:
        String dn = HosLoginJDialog.DEPT_NO_True;
        if(dn.equals("002") || dn.equals("003") ||dn.equals("004") ||dn.equals("005")){
            JOptionPane.showMessageDialog(null,"您没有登录门诊管理页面的权限","提示",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            new CureJFrame().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jB_CureActionPerformed

    private void jB_RoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_RoomActionPerformed
        // TODO add your handling code here:
        String dn = HosLoginJDialog.DEPT_NO_True;
        if(dn.equals("001") || dn.equals("007")){
            new RoomJFrame().setVisible(true);
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null,"您没有登录住院管理页面的权限","提示",JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_jB_RoomActionPerformed

    private void jB_EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_EmployeeActionPerformed
        // TODO add your handling code here:
        String dn = HosLoginJDialog.DEPT_NO_True;
        if(dn.equals("001") || dn.equals("002")){
            new EmployeeJFrame().setVisible(true);
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null,"您没有登录员工管理页面的权限","提示",JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_jB_EmployeeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new HosLoginJDialog().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalJFrame().setVisible(true);
            }
        });
    }
    
     private void setB(){
         ImageIcon img = new ImageIcon("F:/UsingItems/MyHospital/back.jpg");//这是背景图片////////////////////////////////
         JLabel imgLabel = new JLabel(img);//将背景图放在标签里。
           this.getLayeredPane().add(imgLabel, new Integer(Integer.MIN_VALUE));//注意这里是关键，将背景标签添加到jfram的LayeredPane面板里。
           imgLabel.setBounds(0,0,img.getIconWidth(), img.getIconHeight());//设置背景标签的位置
           Container cp=this.getContentPane();
           cp.setLayout(new BorderLayout());
           ((JPanel)cp).setOpaque(false); //注意这里，将内容面板设为透明。这样LayeredPane面板中的背景才能显示出来。
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Cure;
    private javax.swing.JButton jB_Employee;
    private javax.swing.JButton jB_Room;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jL_Hello;
    // End of variables declaration//GEN-END:variables
}
